code --install-extension aaron-bond.better-comments
code --install-extension aeschli.vscode-css-formatter
code --install-extension af4jm.vscode-icalendar
code --install-extension bashmish.es6-string-css
code --install-extension christian-kohler.path-intellisense
code --install-extension dbaeumer.vscode-eslint
code --install-extension deerawan.vscode-faker
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension Fudge.auto-using
code --install-extension glen-84.sass-lint
code --install-extension Gruntfuggly.todo-tree
code --install-extension IBM.output-colorizer
code --install-extension imagio.vscode-dimmer-block
code --install-extension mrmlnc.vscode-scss
code --install-extension MS-CEINTL.vscode-language-pack-de
code --install-extension ms-dotnettools.csharp
code --install-extension octref.vetur
code --install-extension Orta.vscode-jest
code --install-extension pflannery.vscode-versionlens
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension softwaredotcom.swdc-vscode
code --install-extension Tobermory.es6-string-html
code --install-extension Tyriar.lorem-ipsum
